services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    container_name: cnds2024-color-devcontainer
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /workspaces
        consistency: cached
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cnds2024

  redis:
    image: redis:7.0-alpine3.19
    container_name: cnds2024-redis-devcontainer
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    networks:
      - cnds2024

networks:
  cnds2024:
    name: cnds2024-devcontainer
