global:
  imagePullPolicy: IfNotPresent
  logAsJson: true
  defaultPodDisruptionBudget:
    enabled: false
  proxy:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
pilot:
  deploymentLabels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: istio-ambient
  podLabels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: istio-ambient
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  env:
    VERIFY_CERTIFICATE_AT_CLIENT: "true"
    ENABLE_AUTO_SNI: "true"
    PILOT_ENABLE_HBONE: "true"
    CA_TRUSTED_NODE_ACCOUNTS: "istio-system/ztunnel,kube-system/ztunnel"
    PILOT_ENABLE_AMBIENT_CONTROLLERS: "true"
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
telemetry:
  enabled: false
  v2:
    enabled: false
sidecarInjectorWebhook:
  templates:
    sidecar: ""
    gateway: ""
    grpc-simple: ""
    grpc-agent: ""
