apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: trace-collector
spec:
  mode: "deployment"
  config:
    receivers:
      otlp:
        protocols:
          http:

    processors: {}

    exporters:
      debug: {}
      otlp:
        protocol:
          grpc:
              endpoint: jaeger-collector.jaeger:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlp]
